import { FC } from "react";
import Head from "next/head";
import { Formik, Form } from "formik";
import { VStack } from "@chakra-ui/react";

import TextInput from "../components/Atoms/TextInput";
import RichTextInput from "../components/Atoms/RichTextInput";
import Switch from "../components/Atoms/Switch";
import MediaUpload from "../components/Atoms/MediaUpload";
import AddAnother from "../components/Atoms/AddAnother";
import DatePicker from "../components/Atoms/DatePicker";
import TimePicker from "../components/Atoms/TimePicker";
import ApproveButton from "../components/Atoms/ApproveButton";
import RejectButton from "../components/Atoms/RejectButton";
import RemoveButton from "../components/Atoms/RemoveButton";
import FileInput from "../components/Atoms/FileInput";
import Tag from "../components/Atoms/Tag";

import styles from "../styles/Home.module.css";

const DisplaySection: FC = () => {
  return (
    <Form>
      <VStack spacing="1.5rem">
        <TextInput id="xx" name="text" label="XX" />
        <RichTextInput id="fxx" name="richText" label="XX" />
        <Switch id="xxxs" name="switch" />
        <MediaUpload name="image" type="image" />
        <AddAnother onClick={() => {}} />
        <DatePicker name="date" />
        <TimePicker name="time" />
        <ApproveButton />
        <RejectButton />
        <RemoveButton />
        <FileInput name="file" />
        <Tag label="TEXT" />
      </VStack>
    </Form>
  );
};

const Home: FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Form Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Formik
          initialValues={{}}
          onSubmit={() => {}}
          component={DisplaySection}
        />
      </main>
    </div>
  );
};

export default Home;
